// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const getAsset = `-- name: GetAsset :one
SELECT a.id, a.asset_code, a.name, a.asset_type, a.hostname, a.ip_address, a.network_cidr,
       a.operating_system, a.criticality, a.status, a.description, a.attributes,
       d.id AS department_id, d.code AS department_code, d.name AS department_name,
       o.id AS owner_id, o.employee_code AS owner_code, o.display_name AS owner_name,
       l.id AS location_id, l.code AS location_code, l.name AS location_name,
       z.id AS zone_id, z.code AS zone_code
FROM assets a
LEFT JOIN departments d ON d.id = a.department_id
LEFT JOIN employees o ON o.id = a.owner_employee_id
LEFT JOIN locations l ON l.id = a.location_id
LEFT JOIN world_zones z ON z.id = l.zone_id
WHERE a.company_id = $1 AND a.id = $2
`

type GetAssetParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetAssetRow struct {
	ID              uuid.UUID
	AssetCode       string
	Name            string
	AssetType       string
	Hostname        *string
	IPAddress       *netip.Addr
	NetworkCIDR     *netip.Prefix
	OperatingSystem *string
	Criticality     string
	Status          string
	Description     string
	Attributes      []byte
	DepartmentID    *uuid.UUID
	DepartmentCode  *string
	DepartmentName  *string
	OwnerID         *uuid.UUID
	OwnerCode       *string
	OwnerName       *string
	LocationID      *uuid.UUID
	LocationCode    *string
	LocationName    *string
	ZoneID          *uuid.UUID
	ZoneCode        *string
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.CompanyID, arg.ID)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Name,
		&i.AssetType,
		&i.Hostname,
		&i.IPAddress,
		&i.NetworkCIDR,
		&i.OperatingSystem,
		&i.Criticality,
		&i.Status,
		&i.Description,
		&i.Attributes,
		&i.DepartmentID,
		&i.DepartmentCode,
		&i.DepartmentName,
		&i.OwnerID,
		&i.OwnerCode,
		&i.OwnerName,
		&i.LocationID,
		&i.LocationCode,
		&i.LocationName,
		&i.ZoneID,
		&i.ZoneCode,
	)
	return i, err
}

const listAssetNetworks = `-- name: ListAssetNetworks :many
SELECT n.id, n.asset_code, n.name, n.network_cidr
FROM asset_relationships r
JOIN assets n ON n.id = r.target_asset_id
WHERE r.company_id = $1
  AND r.source_asset_id = $2
  AND r.relationship_type = 'CONNECTED_TO'
  AND n.asset_type = 'network'
ORDER BY n.asset_code
`

type ListAssetNetworksParams struct {
	CompanyID uuid.UUID
	AssetID   *uuid.UUID
}

type ListAssetNetworksRow struct {
	ID          uuid.UUID
	AssetCode   string
	Name        string
	NetworkCIDR *netip.Prefix
}

// Networks the asset is connected to (CONNECTED_TO edges to network assets).
func (q *Queries) ListAssetNetworks(ctx context.Context, arg ListAssetNetworksParams) ([]ListAssetNetworksRow, error) {
	rows, err := q.db.Query(ctx, listAssetNetworks, arg.CompanyID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetNetworksRow{}
	for rows.Next() {
		var i ListAssetNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Name,
			&i.NetworkCIDR,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetWorldObjects = `-- name: ListAssetWorldObjects :many
SELECT object_key, name, kind FROM world_objects
WHERE company_id = $1 AND asset_id = $2
ORDER BY object_key
`

type ListAssetWorldObjectsParams struct {
	CompanyID uuid.UUID
	AssetID   *uuid.UUID
}

type ListAssetWorldObjectsRow struct {
	ObjectKey string
	Name      string
	Kind      string
}

func (q *Queries) ListAssetWorldObjects(ctx context.Context, arg ListAssetWorldObjectsParams) ([]ListAssetWorldObjectsRow, error) {
	rows, err := q.db.Query(ctx, listAssetWorldObjects, arg.CompanyID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetWorldObjectsRow{}
	for rows.Next() {
		var i ListAssetWorldObjectsRow
		if err := rows.Scan(&i.ObjectKey, &i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.asset_code, a.name, a.asset_type, a.hostname, a.ip_address, a.network_cidr,
       a.criticality, a.status,
       d.code AS department_code,
       o.employee_code AS owner_code,
       l.code AS location_code
FROM assets a
LEFT JOIN departments d ON d.id = a.department_id
LEFT JOIN employees o ON o.id = a.owner_employee_id
LEFT JOIN locations l ON l.id = a.location_id
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.asset_type = $2::text)
  AND ($3::text IS NULL OR d.code = $3::text)
  AND ($4::text IS NULL
       OR a.name ILIKE $4::text
       OR a.asset_code ILIKE $4::text
       OR a.hostname ILIKE $4::text)
  AND ($5::text IS NULL OR a.asset_code > $5::text)
ORDER BY a.asset_code
LIMIT $6
`

type ListAssetsParams struct {
	CompanyID  uuid.UUID
	AssetType  *string
	Department *string
	Search     *string
	After      *string
	PageSize   int32
}

type ListAssetsRow struct {
	ID             uuid.UUID
	AssetCode      string
	Name           string
	AssetType      string
	Hostname       *string
	IPAddress      *netip.Addr
	NetworkCIDR    *netip.Prefix
	Criticality    string
	Status         string
	DepartmentCode *string
	OwnerCode      *string
	LocationCode   *string
}

// Keyset pagination on asset_code.
func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.CompanyID,
		arg.AssetType,
		arg.Department,
		arg.Search,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Name,
			&i.AssetType,
			&i.Hostname,
			&i.IPAddress,
			&i.NetworkCIDR,
			&i.Criticality,
			&i.Status,
			&i.DepartmentCode,
			&i.OwnerCode,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyRelationships = `-- name: ListCompanyRelationships :many
SELECT id, relationship_type,
       source_employee_id, source_identity_id, source_asset_id,
       target_employee_id, target_identity_id, target_asset_id
FROM asset_relationships
WHERE company_id = $1
ORDER BY id
`

type ListCompanyRelationshipsRow struct {
	ID               uuid.UUID
	RelationshipType string
	SourceEmployeeID *uuid.UUID
	SourceIdentityID *uuid.UUID
	SourceAssetID    *uuid.UUID
	TargetEmployeeID *uuid.UUID
	TargetIdentityID *uuid.UUID
	TargetAssetID    *uuid.UUID
}

func (q *Queries) ListCompanyRelationships(ctx context.Context, companyID uuid.UUID) ([]ListCompanyRelationshipsRow, error) {
	rows, err := q.db.Query(ctx, listCompanyRelationships, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyRelationshipsRow{}
	for rows.Next() {
		var i ListCompanyRelationshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelationshipType,
			&i.SourceEmployeeID,
			&i.SourceIdentityID,
			&i.SourceAssetID,
			&i.TargetEmployeeID,
			&i.TargetIdentityID,
			&i.TargetAssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphAssets = `-- name: ListGraphAssets :many
SELECT id, asset_code, name, asset_type, hostname, criticality
FROM assets
WHERE company_id = $1
`

type ListGraphAssetsRow struct {
	ID          uuid.UUID
	AssetCode   string
	Name        string
	AssetType   string
	Hostname    *string
	Criticality string
}

func (q *Queries) ListGraphAssets(ctx context.Context, companyID uuid.UUID) ([]ListGraphAssetsRow, error) {
	rows, err := q.db.Query(ctx, listGraphAssets, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphAssetsRow{}
	for rows.Next() {
		var i ListGraphAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Name,
			&i.AssetType,
			&i.Hostname,
			&i.Criticality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphEmployees = `-- name: ListGraphEmployees :many
SELECT e.id, e.employee_code, e.display_name, e.job_title, d.code AS department_code
FROM employees e JOIN departments d ON d.id = e.department_id
WHERE e.company_id = $1
`

type ListGraphEmployeesRow struct {
	ID             uuid.UUID
	EmployeeCode   string
	DisplayName    string
	JobTitle       string
	DepartmentCode string
}

func (q *Queries) ListGraphEmployees(ctx context.Context, companyID uuid.UUID) ([]ListGraphEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listGraphEmployees, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphEmployeesRow{}
	for rows.Next() {
		var i ListGraphEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.DisplayName,
			&i.JobTitle,
			&i.DepartmentCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphIdentities = `-- name: ListGraphIdentities :many
SELECT id, username, email, identity_type, privileged, status
FROM enterprise_identities
WHERE company_id = $1
`

type ListGraphIdentitiesRow struct {
	ID           uuid.UUID
	Username     string
	Email        string
	IdentityType string
	Privileged   bool
	Status       string
}

func (q *Queries) ListGraphIdentities(ctx context.Context, companyID uuid.UUID) ([]ListGraphIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listGraphIdentities, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphIdentitiesRow{}
	for rows.Next() {
		var i ListGraphIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.IdentityType,
			&i.Privileged,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
