// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (
    actor_type,
    actor_id,
    action,
    resource_type,
    resource_id,
    result,
    request_id,
    source_ip,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, occurred_at
`

type InsertAuditLogParams struct {
	ActorType    string
	ActorID      *string
	Action       string
	ResourceType string
	ResourceID   *string
	Result       string
	RequestID    *string
	SourceIP     *netip.Addr
	Metadata     []byte
}

type InsertAuditLogRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.RequestID,
		arg.SourceIP,
		arg.Metadata,
	)
	var i InsertAuditLogRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, occurred_at, actor_type, actor_id, action, resource_type, resource_id, result, request_id, source_ip, metadata
FROM audit_logs
WHERE $1::timestamptz IS NULL
   OR (occurred_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY occurred_at DESC, id DESC
LIMIT $3
`

type ListAuditLogsParams struct {
	CursorOccurredAt *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
}

// Newest first with keyset pagination: pass the (occurred_at, id) of the
// last row of the previous page as the cursor, or NULLs for the first page.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.CursorOccurredAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Result,
			&i.RequestID,
			&i.SourceIP,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
