// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveCompany = `-- name: GetActiveCompany :one

SELECT c.id, c.code, c.name, c.legal_name, c.industry, c.description, c.headquarters,
       c.founded_year, c.email_domain,
       s.slug AS scenario_slug, s.name AS scenario_name, s.version AS scenario_version
FROM companies c
JOIN scenarios s ON s.id = c.scenario_id
WHERE s.is_active
`

type GetActiveCompanyRow struct {
	ID              uuid.UUID
	Code            string
	Name            string
	LegalName       string
	Industry        string
	Description     string
	Headquarters    string
	FoundedYear     *int32
	EmailDomain     string
	ScenarioSlug    string
	ScenarioName    string
	ScenarioVersion string
}

// Read side for company, departments and employees. Every query is scoped by
// company_id so one company's data never leaks into another world.
func (q *Queries) GetActiveCompany(ctx context.Context) (GetActiveCompanyRow, error) {
	row := q.db.QueryRow(ctx, getActiveCompany)
	var i GetActiveCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Industry,
		&i.Description,
		&i.Headquarters,
		&i.FoundedYear,
		&i.EmailDomain,
		&i.ScenarioSlug,
		&i.ScenarioName,
		&i.ScenarioVersion,
	)
	return i, err
}

const getCompanyStats = `-- name: GetCompanyStats :one
SELECT
    (SELECT count(*) FROM departments d WHERE d.company_id = $1)::int AS departments,
    (SELECT count(*) FROM employees e WHERE e.company_id = $1)::int  AS employees,
    (SELECT count(*) FROM assets a WHERE a.company_id = $1)::int     AS assets,
    (SELECT count(*) FROM world_zones z WHERE z.company_id = $1)::int AS zones
`

type GetCompanyStatsRow struct {
	Departments int32
	Employees   int32
	Assets      int32
	Zones       int32
}

func (q *Queries) GetCompanyStats(ctx context.Context, companyID uuid.UUID) (GetCompanyStatsRow, error) {
	row := q.db.QueryRow(ctx, getCompanyStats, companyID)
	var i GetCompanyStatsRow
	err := row.Scan(
		&i.Departments,
		&i.Employees,
		&i.Assets,
		&i.Zones,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT e.id, e.employee_code, e.first_name, e.last_name, e.display_name, e.job_title,
       e.status, e.employment_type, e.is_npc, e.greeting,
       d.id AS department_id, d.code AS department_code, d.name AS department_name,
       m.id AS manager_id, m.employee_code AS manager_code, m.display_name AS manager_name,
       l.id AS location_id, l.code AS location_code, l.name AS location_name,
       z.id AS zone_id, z.code AS zone_code
FROM employees e
JOIN departments d ON d.id = e.department_id
LEFT JOIN employees m ON m.id = e.manager_id
LEFT JOIN locations l ON l.id = e.home_location_id
LEFT JOIN world_zones z ON z.id = l.zone_id
WHERE e.company_id = $1 AND e.id = $2
`

type GetEmployeeParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetEmployeeRow struct {
	ID             uuid.UUID
	EmployeeCode   string
	FirstName      string
	LastName       string
	DisplayName    string
	JobTitle       string
	Status         string
	EmploymentType string
	IsNpc          bool
	Greeting       string
	DepartmentID   uuid.UUID
	DepartmentCode string
	DepartmentName string
	ManagerID      *uuid.UUID
	ManagerCode    *string
	ManagerName    *string
	LocationID     *uuid.UUID
	LocationCode   *string
	LocationName   *string
	ZoneID         *uuid.UUID
	ZoneCode       *string
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.CompanyID, arg.ID)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.JobTitle,
		&i.Status,
		&i.EmploymentType,
		&i.IsNpc,
		&i.Greeting,
		&i.DepartmentID,
		&i.DepartmentCode,
		&i.DepartmentName,
		&i.ManagerID,
		&i.ManagerCode,
		&i.ManagerName,
		&i.LocationID,
		&i.LocationCode,
		&i.LocationName,
		&i.ZoneID,
		&i.ZoneCode,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT d.id, d.code, d.name, d.description,
       p.code         AS parent_code,
       h.id           AS head_id,
       h.display_name AS head_name,
       h.job_title    AS head_title,
       (SELECT count(*) FROM employees e WHERE e.department_id = d.id)::int AS employee_count
FROM departments d
LEFT JOIN departments p ON p.id = d.parent_id
LEFT JOIN employees h ON h.id = d.head_employee_id
WHERE d.company_id = $1
ORDER BY d.sort_order, d.code
`

type ListDepartmentsRow struct {
	ID            uuid.UUID
	Code          string
	Name          string
	Description   string
	ParentCode    *string
	HeadID        *uuid.UUID
	HeadName      *string
	HeadTitle     *string
	EmployeeCount int32
}

func (q *Queries) ListDepartments(ctx context.Context, companyID uuid.UUID) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsRow{}
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ParentCode,
			&i.HeadID,
			&i.HeadName,
			&i.HeadTitle,
			&i.EmployeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectReports = `-- name: ListDirectReports :many
SELECT id, employee_code, display_name, job_title
FROM employees
WHERE company_id = $1 AND manager_id = $2
ORDER BY employee_code
`

type ListDirectReportsParams struct {
	CompanyID uuid.UUID
	ManagerID *uuid.UUID
}

type ListDirectReportsRow struct {
	ID           uuid.UUID
	EmployeeCode string
	DisplayName  string
	JobTitle     string
}

func (q *Queries) ListDirectReports(ctx context.Context, arg ListDirectReportsParams) ([]ListDirectReportsRow, error) {
	rows, err := q.db.Query(ctx, listDirectReports, arg.CompanyID, arg.ManagerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectReportsRow{}
	for rows.Next() {
		var i ListDirectReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.DisplayName,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeAssets = `-- name: ListEmployeeAssets :many
SELECT id, asset_code, name, asset_type, hostname
FROM assets
WHERE company_id = $1 AND owner_employee_id = $2
ORDER BY asset_code
`

type ListEmployeeAssetsParams struct {
	CompanyID  uuid.UUID
	EmployeeID *uuid.UUID
}

type ListEmployeeAssetsRow struct {
	ID        uuid.UUID
	AssetCode string
	Name      string
	AssetType string
	Hostname  *string
}

func (q *Queries) ListEmployeeAssets(ctx context.Context, arg ListEmployeeAssetsParams) ([]ListEmployeeAssetsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeAssets, arg.CompanyID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeAssetsRow{}
	for rows.Next() {
		var i ListEmployeeAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Name,
			&i.AssetType,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeIdentities = `-- name: ListEmployeeIdentities :many
SELECT i.id, i.username, i.email, i.identity_type, i.status, i.mfa_enabled, i.privileged, i.expires_at,
       COALESCE(
           (SELECT array_agg(g.asset_code ORDER BY g.asset_code)
            FROM asset_relationships r JOIN assets g ON g.id = r.target_asset_id
            WHERE r.source_identity_id = i.id AND r.relationship_type = 'MEMBER_OF'),
           '{}')::text[] AS groups
FROM enterprise_identities i
WHERE i.company_id = $1 AND i.employee_id = $2
ORDER BY i.username
`

type ListEmployeeIdentitiesParams struct {
	CompanyID  uuid.UUID
	EmployeeID *uuid.UUID
}

type ListEmployeeIdentitiesRow struct {
	ID           uuid.UUID
	Username     string
	Email        string
	IdentityType string
	Status       string
	MfaEnabled   bool
	Privileged   bool
	ExpiresAt    *time.Time
	Groups       []string
}

func (q *Queries) ListEmployeeIdentities(ctx context.Context, arg ListEmployeeIdentitiesParams) ([]ListEmployeeIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeIdentities, arg.CompanyID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeIdentitiesRow{}
	for rows.Next() {
		var i ListEmployeeIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.IdentityType,
			&i.Status,
			&i.MfaEnabled,
			&i.Privileged,
			&i.ExpiresAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeSchedule = `-- name: ListEmployeeSchedule :many
SELECT s.weekday, s.starts_at, s.ends_at, s.activity, l.code AS location_code
FROM employee_schedules s
JOIN employees e ON e.id = s.employee_id
LEFT JOIN locations l ON l.id = s.location_id
WHERE e.company_id = $1 AND s.employee_id = $2
ORDER BY s.weekday, s.starts_at
`

type ListEmployeeScheduleParams struct {
	CompanyID  uuid.UUID
	EmployeeID uuid.UUID
}

type ListEmployeeScheduleRow struct {
	Weekday      int32
	StartsAt     pgtype.Time
	EndsAt       pgtype.Time
	Activity     string
	LocationCode *string
}

func (q *Queries) ListEmployeeSchedule(ctx context.Context, arg ListEmployeeScheduleParams) ([]ListEmployeeScheduleRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeSchedule, arg.CompanyID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeScheduleRow{}
	for rows.Next() {
		var i ListEmployeeScheduleRow
		if err := rows.Scan(
			&i.Weekday,
			&i.StartsAt,
			&i.EndsAt,
			&i.Activity,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.employee_code, e.display_name, e.job_title, e.status, e.employment_type, e.is_npc,
       d.code AS department_code, d.name AS department_name,
       l.code AS location_code
FROM employees e
JOIN departments d ON d.id = e.department_id
LEFT JOIN locations l ON l.id = e.home_location_id
WHERE e.company_id = $1
  AND ($2::text IS NULL OR d.code = $2::text)
  AND ($3::text IS NULL
       OR e.display_name ILIKE $3::text
       OR e.job_title ILIKE $3::text
       OR e.employee_code ILIKE $3::text)
  AND ($4::text IS NULL OR e.employee_code > $4::text)
ORDER BY e.employee_code
LIMIT $5
`

type ListEmployeesParams struct {
	CompanyID  uuid.UUID
	Department *string
	Search     *string
	After      *string
	PageSize   int32
}

type ListEmployeesRow struct {
	ID             uuid.UUID
	EmployeeCode   string
	DisplayName    string
	JobTitle       string
	Status         string
	EmploymentType string
	IsNpc          bool
	DepartmentCode string
	DepartmentName string
	LocationCode   *string
}

// Keyset pagination on employee_code. search is an ILIKE pattern built and
// escaped by the caller.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.CompanyID,
		arg.Department,
		arg.Search,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.DisplayName,
			&i.JobTitle,
			&i.Status,
			&i.EmploymentType,
			&i.IsNpc,
			&i.DepartmentCode,
			&i.DepartmentName,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
