// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET state = 'running',
    attempts = attempts + 1,
    locked_by = $1::text,
    locked_until = now() + make_interval(secs => $2::float8)
WHERE id = (
    SELECT j.id FROM jobs j
    WHERE j.kind = ANY($3::text[])
      AND ((j.state = 'queued' AND j.run_after <= now())
        OR (j.state = 'running' AND j.locked_until < now()))
    ORDER BY j.run_after, j.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, payload, attempts, max_attempts
`

type ClaimJobParams struct {
	Worker       string
	LeaseSeconds float64
	Kinds        []string
}

type ClaimJobRow struct {
	ID          uuid.UUID
	Kind        string
	Payload     []byte
	Attempts    int32
	MaxAttempts int32
}

// Claims the oldest runnable job of the given kinds: a queued job that is
// due, or a running job whose lease expired (its worker died). SKIP LOCKED
// lets any number of workers claim concurrently without blocking.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.Worker, arg.LeaseSeconds, arg.Kinds)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Attempts,
		&i.MaxAttempts,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs SET state = 'succeeded', locked_by = NULL, locked_until = NULL, last_error = NULL
WHERE id = $1 AND locked_by = $2::text AND state = 'running'
`

type CompleteJobParams struct {
	ID     uuid.UUID
	Worker string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countJobsByState = `-- name: CountJobsByState :many
SELECT kind, state, count(*)::int AS jobs FROM jobs GROUP BY kind, state ORDER BY kind, state
`

type CountJobsByStateRow struct {
	Kind  string
	State string
	Jobs  int32
}

func (q *Queries) CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error) {
	rows, err := q.db.Query(ctx, countJobsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStateRow{}
	for rows.Next() {
		var i CountJobsByStateRow
		if err := rows.Scan(&i.Kind, &i.State, &i.Jobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (kind, payload, run_after, max_attempts)
VALUES ($1, $2, COALESCE($3::timestamptz, now()), $4)
RETURNING id
`

type EnqueueJobParams struct {
	Kind        string
	Payload     []byte
	RunAfter    *time.Time
	MaxAttempts int32
}

// Durable job queue (see internal/jobs).
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Kind,
		arg.Payload,
		arg.RunAfter,
		arg.MaxAttempts,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs SET locked_until = now() + make_interval(secs => $1::float8)
WHERE id = $2 AND locked_by = $3::text AND state = 'running'
`

type ExtendJobLeaseParams struct {
	LeaseSeconds float64
	ID           uuid.UUID
	Worker       string
}

// Heartbeat. Zero rows means the lease was lost (another worker took over).
func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease, arg.LeaseSeconds, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failJob = `-- name: FailJob :one
UPDATE jobs
SET state = CASE WHEN $1::boolean OR attempts >= max_attempts THEN 'failed' ELSE 'queued' END,
    run_after = now() + make_interval(secs => $2::float8),
    last_error = $3::text,
    locked_by = NULL,
    locked_until = NULL
WHERE id = $4 AND locked_by = $5::text AND state = 'running'
RETURNING state
`

type FailJobParams struct {
	Permanent      bool
	BackoffSeconds float64
	LastError      string
	ID             uuid.UUID
	Worker         string
}

// Records a failed attempt: the job is retried after a backoff unless the
// error is permanent or attempts are exhausted.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (string, error) {
	row := q.db.QueryRow(ctx, failJob,
		arg.Permanent,
		arg.BackoffSeconds,
		arg.LastError,
		arg.ID,
		arg.Worker,
	)
	var state string
	err := row.Scan(&state)
	return state, err
}

const pruneFinishedJobs = `-- name: PruneFinishedJobs :execrows
DELETE FROM jobs
WHERE (state = 'succeeded' AND updated_at < now() - make_interval(secs => $1::float8))
   OR (state = 'failed' AND updated_at < now() - make_interval(secs => $2::float8))
`

type PruneFinishedJobsParams struct {
	SucceededAfterSeconds float64
	FailedAfterSeconds    float64
}

// Succeeded jobs are kept for a while for operators; failed ones longer.
func (q *Queries) PruneFinishedJobs(ctx context.Context, arg PruneFinishedJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneFinishedJobs, arg.SucceededAfterSeconds, arg.FailedAfterSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseJob = `-- name: ReleaseJob :execrows
UPDATE jobs SET state = 'queued', attempts = GREATEST(attempts - 1, 0), run_after = now(),
    locked_by = NULL, locked_until = NULL
WHERE id = $1 AND locked_by = $2::text AND state = 'running'
`

type ReleaseJobParams struct {
	ID     uuid.UUID
	Worker string
}

// Gives an interrupted job back (worker shutdown) without consuming an attempt.
func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseJob, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const secondsUntilNextJob = `-- name: SecondsUntilNextJob :one
SELECT COALESCE(GREATEST(EXTRACT(EPOCH FROM min(CASE WHEN state = 'queued' THEN run_after ELSE locked_until END) - now()), 0), -1)::float8 AS seconds
FROM jobs
WHERE kind = ANY($1::text[]) AND state IN ('queued', 'running')
`

// How long until a job of these kinds becomes claimable (a retry's backoff
// ends or a lease expires); -1 when none is pending. Computed by the
// database so worker clock skew does not matter.
func (q *Queries) SecondsUntilNextJob(ctx context.Context, kinds []string) (float64, error) {
	row := q.db.QueryRow(ctx, secondsUntilNextJob, kinds)
	var seconds float64
	err := row.Scan(&seconds)
	return seconds, err
}
