// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID           uuid.UUID
	OccurredAt   time.Time
	ActorType    string
	ActorID      *string
	Action       string
	ResourceType string
	ResourceID   *string
	Result       string
	RequestID    *string
	SourceIP     *netip.Addr
	Metadata     []byte
}

type Player struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID              uuid.UUID
	KeycloakSubject string
	Username        string
	Email           *string
	EmailVerified   bool
	FullName        *string
	Status          string
	LastSeenAt      time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
