// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID              uuid.UUID
	CompanyID       uuid.UUID
	AssetCode       string
	Name            string
	AssetType       string
	Hostname        *string
	IPAddress       *netip.Addr
	NetworkCIDR     *netip.Prefix
	OperatingSystem *string
	Criticality     string
	Status          string
	DepartmentID    *uuid.UUID
	OwnerEmployeeID *uuid.UUID
	LocationID      *uuid.UUID
	Description     string
	Attributes      []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AssetRelationship struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	RelationshipType string
	SourceEmployeeID *uuid.UUID
	SourceIdentityID *uuid.UUID
	SourceAssetID    *uuid.UUID
	TargetEmployeeID *uuid.UUID
	TargetIdentityID *uuid.UUID
	TargetAssetID    *uuid.UUID
	CreatedAt        time.Time
}

type AuditLog struct {
	ID           uuid.UUID
	OccurredAt   time.Time
	ActorType    string
	ActorID      *string
	Action       string
	ResourceType string
	ResourceID   *string
	Result       string
	RequestID    *string
	SourceIP     *netip.Addr
	Metadata     []byte
}

type CareerLevel struct {
	ID          uuid.UUID
	Rank        int32
	Code        string
	Name        string
	Description string
	MinXp       int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Company struct {
	ID           uuid.UUID
	ScenarioID   uuid.UUID
	Code         string
	Name         string
	LegalName    string
	Industry     string
	Description  string
	Headquarters string
	FoundedYear  *int32
	EmailDomain  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Department struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	Code           string
	Name           string
	Description    string
	ParentID       *uuid.UUID
	SortOrder      int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HeadEmployeeID *uuid.UUID
}

type Discovery struct {
	PlayerID      uuid.UUID
	AssetID       uuid.UUID
	ObjectID      *uuid.UUID
	DiscoveredVia string
	DiscoveredAt  time.Time
}

type Employee struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	EmployeeCode   string
	FirstName      string
	LastName       string
	DisplayName    string
	JobTitle       string
	DepartmentID   uuid.UUID
	ManagerID      *uuid.UUID
	HomeLocationID *uuid.UUID
	EmploymentType string
	Status         string
	IsNpc          bool
	Persona        string
	Greeting       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type EmployeeSchedule struct {
	ID         uuid.UUID
	EmployeeID uuid.UUID
	Weekday    int32
	StartsAt   pgtype.Time
	EndsAt     pgtype.Time
	LocationID *uuid.UUID
	Activity   string
}

type EnterpriseIdentity struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	EmployeeID   *uuid.UUID
	Username     string
	Email        string
	IdentityType string
	Status       string
	MfaEnabled   bool
	Privileged   bool
	ExpiresAt    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Interaction struct {
	ID              uuid.UUID
	PlayerID        uuid.UUID
	CompanyID       uuid.UUID
	InteractionType string
	ZoneID          *uuid.UUID
	ObjectID        *uuid.UUID
	EmployeeID      *uuid.UUID
	Outcome         string
	Reason          *string
	XpAwarded       int32
	RequestID       *string
	CreatedAt       time.Time
}

type Location struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	ZoneID       uuid.UUID
	Code         string
	Name         string
	Kind         string
	DepartmentID *uuid.UUID
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Player struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlayerProgress struct {
	PlayerID      uuid.UUID
	Xp            int32
	CurrentZoneID *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PlayerZoneUnlock struct {
	PlayerID   uuid.UUID
	ZoneID     uuid.UUID
	Source     string
	UnlockedAt time.Time
}

type Scenario struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Version     string
	Description string
	Status      string
	IsActive    bool
	ContentHash string
	ImportedAt  time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID              uuid.UUID
	KeycloakSubject string
	Username        string
	Email           *string
	EmailVerified   bool
	FullName        *string
	Status          string
	LastSeenAt      time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WorldObject struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	LocationID    uuid.UUID
	ObjectKey     string
	Name          string
	Kind          string
	AssetID       *uuid.UUID
	LeadsToZoneID *uuid.UUID
	Interactions  []string
	Description   string
	Content       string
	Attributes    []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type WorldZone struct {
	ID                 uuid.UUID
	CompanyID          uuid.UUID
	Code               string
	Name               string
	Kind               string
	ParentID           *uuid.UUID
	Description        string
	UnlockedByDefault  bool
	RequiredCareerRank int32
	SortOrder          int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
