// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, title, body, data, read_at, created_at
`

type InsertNotificationParams struct {
	UserID uuid.UUID
	Type   string
	Title  string
	Body   string
	Data   []byte
}

type InsertNotificationRow struct {
	ID        uuid.UUID
	Type      string
	Title     string
	Body      string
	Data      []byte
	ReadAt    *time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (InsertNotificationRow, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i InsertNotificationRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, title, body, data, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND (NOT $2::boolean OR read_at IS NULL)
  AND ($3::uuid IS NULL OR id < $3::uuid)
ORDER BY id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
	BeforeID   *uuid.UUID
	PageSize   int32
}

type ListNotificationsRow struct {
	ID        uuid.UUID
	Type      string
	Title     string
	Body      string
	Data      []byte
	ReadAt    *time.Time
	CreatedAt time.Time
}

// Newest first; pass the last id of the previous page as before_id.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND user_id = $2
RETURNING id, read_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type MarkNotificationReadRow struct {
	ID     uuid.UUID
	ReadAt *time.Time
}

// Scoped by user: a user can never mark someone else's notification.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (MarkNotificationReadRow, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i MarkNotificationReadRow
	err := row.Scan(&i.ID, &i.ReadAt)
	return i, err
}
