// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const addPlayerXP = `-- name: AddPlayerXP :one
UPDATE player_progress SET xp = xp + $1 WHERE player_id = $2 RETURNING xp
`

type AddPlayerXPParams struct {
	Xp       int32
	PlayerID uuid.UUID
}

func (q *Queries) AddPlayerXP(ctx context.Context, arg AddPlayerXPParams) (int32, error) {
	row := q.db.QueryRow(ctx, addPlayerXP, arg.Xp, arg.PlayerID)
	var xp int32
	err := row.Scan(&xp)
	return xp, err
}

const countDiscoveries = `-- name: CountDiscoveries :one
SELECT count(*)::int FROM discoveries d
JOIN assets a ON a.id = d.asset_id
WHERE d.player_id = $1 AND a.company_id = $2
`

type CountDiscoveriesParams struct {
	PlayerID  uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) CountDiscoveries(ctx context.Context, arg CountDiscoveriesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countDiscoveries, arg.PlayerID, arg.CompanyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const ensurePlayerProgress = `-- name: EnsurePlayerProgress :exec
INSERT INTO player_progress (player_id) VALUES ($1) ON CONFLICT (player_id) DO NOTHING
`

func (q *Queries) EnsurePlayerProgress(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensurePlayerProgress, playerID)
	return err
}

const getInteractionNPC = `-- name: GetInteractionNPC :one
SELECT e.id, e.employee_code, e.display_name, e.job_title, e.greeting, e.is_npc, e.status,
       l.zone_id
FROM employees e
LEFT JOIN locations l ON l.id = e.home_location_id
WHERE e.company_id = $1 AND e.id = $2
`

type GetInteractionNPCParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetInteractionNPCRow struct {
	ID           uuid.UUID
	EmployeeCode string
	DisplayName  string
	JobTitle     string
	Greeting     string
	IsNpc        bool
	Status       string
	ZoneID       *uuid.UUID
}

func (q *Queries) GetInteractionNPC(ctx context.Context, arg GetInteractionNPCParams) (GetInteractionNPCRow, error) {
	row := q.db.QueryRow(ctx, getInteractionNPC, arg.CompanyID, arg.ID)
	var i GetInteractionNPCRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.DisplayName,
		&i.JobTitle,
		&i.Greeting,
		&i.IsNpc,
		&i.Status,
		&i.ZoneID,
	)
	return i, err
}

const getInteractionObject = `-- name: GetInteractionObject :one
SELECT o.id, o.object_key, o.name, o.kind, o.interactions, o.description, o.content,
       l.zone_id, l.code AS location_code,
       o.leads_to_zone_id,
       a.id AS asset_id, a.asset_code, a.name AS asset_name, a.asset_type, a.hostname,
       a.ip_address, a.operating_system, a.criticality,
       ow.employee_code AS owner_code, ow.display_name AS owner_name
FROM world_objects o
JOIN locations l ON l.id = o.location_id
LEFT JOIN assets a ON a.id = o.asset_id
LEFT JOIN employees ow ON ow.id = a.owner_employee_id
WHERE o.company_id = $1 AND o.object_key = $2
`

type GetInteractionObjectParams struct {
	CompanyID uuid.UUID
	ObjectKey string
}

type GetInteractionObjectRow struct {
	ID              uuid.UUID
	ObjectKey       string
	Name            string
	Kind            string
	Interactions    []string
	Description     string
	Content         string
	ZoneID          uuid.UUID
	LocationCode    string
	LeadsToZoneID   *uuid.UUID
	AssetID         *uuid.UUID
	AssetCode       *string
	AssetName       *string
	AssetType       *string
	Hostname        *string
	IPAddress       *netip.Addr
	OperatingSystem *string
	Criticality     *string
	OwnerCode       *string
	OwnerName       *string
}

func (q *Queries) GetInteractionObject(ctx context.Context, arg GetInteractionObjectParams) (GetInteractionObjectRow, error) {
	row := q.db.QueryRow(ctx, getInteractionObject, arg.CompanyID, arg.ObjectKey)
	var i GetInteractionObjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Name,
		&i.Kind,
		&i.Interactions,
		&i.Description,
		&i.Content,
		&i.ZoneID,
		&i.LocationCode,
		&i.LeadsToZoneID,
		&i.AssetID,
		&i.AssetCode,
		&i.AssetName,
		&i.AssetType,
		&i.Hostname,
		&i.IPAddress,
		&i.OperatingSystem,
		&i.Criticality,
		&i.OwnerCode,
		&i.OwnerName,
	)
	return i, err
}

const getPlayerProgress = `-- name: GetPlayerProgress :one
SELECT player_id, xp, current_zone_id FROM player_progress WHERE player_id = $1
`

type GetPlayerProgressRow struct {
	PlayerID      uuid.UUID
	Xp            int32
	CurrentZoneID *uuid.UUID
}

func (q *Queries) GetPlayerProgress(ctx context.Context, playerID uuid.UUID) (GetPlayerProgressRow, error) {
	row := q.db.QueryRow(ctx, getPlayerProgress, playerID)
	var i GetPlayerProgressRow
	err := row.Scan(&i.PlayerID, &i.Xp, &i.CurrentZoneID)
	return i, err
}

const grantZoneUnlock = `-- name: GrantZoneUnlock :exec
INSERT INTO player_zone_unlocks (player_id, zone_id, source)
VALUES ($1, $2, $3)
ON CONFLICT (player_id, zone_id) DO NOTHING
`

type GrantZoneUnlockParams struct {
	PlayerID uuid.UUID
	ZoneID   uuid.UUID
	Source   string
}

func (q *Queries) GrantZoneUnlock(ctx context.Context, arg GrantZoneUnlockParams) error {
	_, err := q.db.Exec(ctx, grantZoneUnlock, arg.PlayerID, arg.ZoneID, arg.Source)
	return err
}

const insertDiscovery = `-- name: InsertDiscovery :one
INSERT INTO discoveries (player_id, asset_id, object_id, discovered_via)
VALUES ($1, $2, $3, $4)
ON CONFLICT (player_id, asset_id) DO NOTHING
RETURNING asset_id
`

type InsertDiscoveryParams struct {
	PlayerID      uuid.UUID
	AssetID       uuid.UUID
	ObjectID      *uuid.UUID
	DiscoveredVia string
}

// Returns no rows if the player already discovered the asset.
func (q *Queries) InsertDiscovery(ctx context.Context, arg InsertDiscoveryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDiscovery,
		arg.PlayerID,
		arg.AssetID,
		arg.ObjectID,
		arg.DiscoveredVia,
	)
	var asset_id uuid.UUID
	err := row.Scan(&asset_id)
	return asset_id, err
}

const insertInteraction = `-- name: InsertInteraction :one
INSERT INTO interactions (
    player_id, company_id, interaction_type, zone_id, object_id, employee_id,
    outcome, reason, xp_awarded, request_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
RETURNING id, created_at
`

type InsertInteractionParams struct {
	PlayerID        uuid.UUID
	CompanyID       uuid.UUID
	InteractionType string
	ZoneID          *uuid.UUID
	ObjectID        *uuid.UUID
	EmployeeID      *uuid.UUID
	Outcome         string
	Reason          *string
	XpAwarded       int32
	RequestID       *string
}

type InsertInteractionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertInteraction(ctx context.Context, arg InsertInteractionParams) (InsertInteractionRow, error) {
	row := q.db.QueryRow(ctx, insertInteraction,
		arg.PlayerID,
		arg.CompanyID,
		arg.InteractionType,
		arg.ZoneID,
		arg.ObjectID,
		arg.EmployeeID,
		arg.Outcome,
		arg.Reason,
		arg.XpAwarded,
		arg.RequestID,
	)
	var i InsertInteractionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listCareerLevels = `-- name: ListCareerLevels :many
SELECT rank, code, name, description, min_xp FROM career_levels ORDER BY rank
`

type ListCareerLevelsRow struct {
	Rank        int32
	Code        string
	Name        string
	Description string
	MinXp       int32
}

func (q *Queries) ListCareerLevels(ctx context.Context) ([]ListCareerLevelsRow, error) {
	rows, err := q.db.Query(ctx, listCareerLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCareerLevelsRow{}
	for rows.Next() {
		var i ListCareerLevelsRow
		if err := rows.Scan(
			&i.Rank,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.MinXp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneRules = `-- name: ListZoneRules :many
SELECT id, code, name, parent_id, unlocked_by_default, required_career_rank
FROM world_zones
WHERE company_id = $1
`

type ListZoneRulesRow struct {
	ID                 uuid.UUID
	Code               string
	Name               string
	ParentID           *uuid.UUID
	UnlockedByDefault  bool
	RequiredCareerRank int32
}

func (q *Queries) ListZoneRules(ctx context.Context, companyID uuid.UUID) ([]ListZoneRulesRow, error) {
	rows, err := q.db.Query(ctx, listZoneRules, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZoneRulesRow{}
	for rows.Next() {
		var i ListZoneRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.UnlockedByDefault,
			&i.RequiredCareerRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneUnlocks = `-- name: ListZoneUnlocks :many
SELECT u.zone_id, z.code AS zone_code, u.source, u.unlocked_at
FROM player_zone_unlocks u
JOIN world_zones z ON z.id = u.zone_id
WHERE u.player_id = $1 AND z.company_id = $2
ORDER BY z.code
`

type ListZoneUnlocksParams struct {
	PlayerID  uuid.UUID
	CompanyID uuid.UUID
}

type ListZoneUnlocksRow struct {
	ZoneID     uuid.UUID
	ZoneCode   string
	Source     string
	UnlockedAt time.Time
}

func (q *Queries) ListZoneUnlocks(ctx context.Context, arg ListZoneUnlocksParams) ([]ListZoneUnlocksRow, error) {
	rows, err := q.db.Query(ctx, listZoneUnlocks, arg.PlayerID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZoneUnlocksRow{}
	for rows.Next() {
		var i ListZoneUnlocksRow
		if err := rows.Scan(
			&i.ZoneID,
			&i.ZoneCode,
			&i.Source,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayerProgress = `-- name: LockPlayerProgress :one
SELECT player_id, xp, current_zone_id FROM player_progress WHERE player_id = $1 FOR UPDATE
`

type LockPlayerProgressRow struct {
	PlayerID      uuid.UUID
	Xp            int32
	CurrentZoneID *uuid.UUID
}

// Serialises a player's state changes for the duration of the transaction.
func (q *Queries) LockPlayerProgress(ctx context.Context, playerID uuid.UUID) (LockPlayerProgressRow, error) {
	row := q.db.QueryRow(ctx, lockPlayerProgress, playerID)
	var i LockPlayerProgressRow
	err := row.Scan(&i.PlayerID, &i.Xp, &i.CurrentZoneID)
	return i, err
}

const setCurrentZone = `-- name: SetCurrentZone :exec
UPDATE player_progress SET current_zone_id = $1 WHERE player_id = $2
`

type SetCurrentZoneParams struct {
	ZoneID   *uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) SetCurrentZone(ctx context.Context, arg SetCurrentZoneParams) error {
	_, err := q.db.Exec(ctx, setCurrentZone, arg.ZoneID, arg.PlayerID)
	return err
}
