// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error)
	// Newest first with keyset pagination: pass the (occurred_at, id) of the
	// last row of the previous page as the cursor, or NULLs for the first page.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
}

var _ Querier = (*Queries)(nil)
