// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ranges.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRangesByState = `-- name: CountRangesByState :many
SELECT state, count(*)::int AS ranges FROM ranges GROUP BY state ORDER BY state
`

type CountRangesByStateRow struct {
	State  string
	Ranges int32
}

func (q *Queries) CountRangesByState(ctx context.Context) ([]CountRangesByStateRow, error) {
	rows, err := q.db.Query(ctx, countRangesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRangesByStateRow{}
	for rows.Next() {
		var i CountRangesByStateRow
		if err := rows.Scan(&i.State, &i.Ranges); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRange = `-- name: CreateRange :one
INSERT INTO ranges (id, player_id, template_id, namespace, requested_cpu_millis, requested_memory_mib, requested_storage_mib)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, player_id, template_id, state, namespace, requested_cpu_millis, requested_memory_mib, requested_storage_mib, failure_reason, expires_at, ready_at, destroyed_at, created_at, updated_at
`

type CreateRangeParams struct {
	ID         uuid.UUID
	PlayerID   uuid.UUID
	TemplateID uuid.UUID
	Namespace  string
	CpuMillis  int32
	MemoryMib  int32
	StorageMib int32
}

func (q *Queries) CreateRange(ctx context.Context, arg CreateRangeParams) (Range, error) {
	row := q.db.QueryRow(ctx, createRange,
		arg.ID,
		arg.PlayerID,
		arg.TemplateID,
		arg.Namespace,
		arg.CpuMillis,
		arg.MemoryMib,
		arg.StorageMib,
	)
	var i Range
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TemplateID,
		&i.State,
		&i.Namespace,
		&i.RequestedCpuMillis,
		&i.RequestedMemoryMib,
		&i.RequestedStorageMib,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.ReadyAt,
		&i.DestroyedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateStaleRangeTemplates = `-- name: DeactivateStaleRangeTemplates :execrows
UPDATE range_templates SET active = false
WHERE scenario_id = $1 AND active AND NOT (slug = ANY($2::text[]))
`

type DeactivateStaleRangeTemplatesParams struct {
	ScenarioID uuid.UUID
	Keep       []string
}

// Templates removed from the scenario stay for existing ranges but cannot
// be used for new ones.
func (q *Queries) DeactivateStaleRangeTemplates(ctx context.Context, arg DeactivateStaleRangeTemplatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateStaleRangeTemplates, arg.ScenarioID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveRangeTemplateBySlug = `-- name: GetActiveRangeTemplateBySlug :one
SELECT t.id, t.slug, t.name, t.description, t.ttl_seconds, t.cpu_millis, t.memory_mib, t.storage_mib, t.spec
FROM range_templates t
JOIN scenarios s ON s.id = t.scenario_id
WHERE s.is_active AND t.active AND t.slug = $1
`

type GetActiveRangeTemplateBySlugRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description string
	TtlSeconds  int32
	CpuMillis   int32
	MemoryMib   int32
	StorageMib  int32
	Spec        []byte
}

func (q *Queries) GetActiveRangeTemplateBySlug(ctx context.Context, slug string) (GetActiveRangeTemplateBySlugRow, error) {
	row := q.db.QueryRow(ctx, getActiveRangeTemplateBySlug, slug)
	var i GetActiveRangeTemplateBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.TtlSeconds,
		&i.CpuMillis,
		&i.MemoryMib,
		&i.StorageMib,
		&i.Spec,
	)
	return i, err
}

const getRangeTemplate = `-- name: GetRangeTemplate :one
SELECT id, scenario_id, slug, name, description, ttl_seconds, cpu_millis, memory_mib, storage_mib, spec, active, created_at, updated_at FROM range_templates WHERE id = $1
`

func (q *Queries) GetRangeTemplate(ctx context.Context, id uuid.UUID) (RangeTemplate, error) {
	row := q.db.QueryRow(ctx, getRangeTemplate, id)
	var i RangeTemplate
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.TtlSeconds,
		&i.CpuMillis,
		&i.MemoryMib,
		&i.StorageMib,
		&i.Spec,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRangeView = `-- name: GetRangeView :one
SELECT r.id, r.player_id, r.template_id, r.state, r.namespace, r.requested_cpu_millis, r.requested_memory_mib, r.requested_storage_mib, r.failure_reason, r.expires_at, r.ready_at, r.destroyed_at, r.created_at, r.updated_at, t.slug AS template_slug, t.name AS template_name, p.user_id
FROM ranges r
JOIN range_templates t ON t.id = r.template_id
JOIN players p ON p.id = r.player_id
WHERE r.id = $1
`

type GetRangeViewRow struct {
	Range        Range
	TemplateSlug string
	TemplateName string
	UserID       uuid.UUID
}

func (q *Queries) GetRangeView(ctx context.Context, id uuid.UUID) (GetRangeViewRow, error) {
	row := q.db.QueryRow(ctx, getRangeView, id)
	var i GetRangeViewRow
	err := row.Scan(
		&i.Range.ID,
		&i.Range.PlayerID,
		&i.Range.TemplateID,
		&i.Range.State,
		&i.Range.Namespace,
		&i.Range.RequestedCpuMillis,
		&i.Range.RequestedMemoryMib,
		&i.Range.RequestedStorageMib,
		&i.Range.FailureReason,
		&i.Range.ExpiresAt,
		&i.Range.ReadyAt,
		&i.Range.DestroyedAt,
		&i.Range.CreatedAt,
		&i.Range.UpdatedAt,
		&i.TemplateSlug,
		&i.TemplateName,
		&i.UserID,
	)
	return i, err
}

const insertRangeTransition = `-- name: InsertRangeTransition :exec
INSERT INTO range_state_transitions (range_id, from_state, to_state, reason, actor)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRangeTransitionParams struct {
	RangeID   uuid.UUID
	FromState *string
	ToState   string
	Reason    string
	Actor     string
}

func (q *Queries) InsertRangeTransition(ctx context.Context, arg InsertRangeTransitionParams) error {
	_, err := q.db.Exec(ctx, insertRangeTransition,
		arg.RangeID,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.Actor,
	)
	return err
}

const listActiveRangeTemplates = `-- name: ListActiveRangeTemplates :many
SELECT t.id, t.slug, t.name, t.description, t.ttl_seconds, t.cpu_millis, t.memory_mib, t.storage_mib, t.spec
FROM range_templates t
JOIN scenarios s ON s.id = t.scenario_id
WHERE s.is_active AND t.active
ORDER BY t.cpu_millis, t.slug
`

type ListActiveRangeTemplatesRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description string
	TtlSeconds  int32
	CpuMillis   int32
	MemoryMib   int32
	StorageMib  int32
	Spec        []byte
}

func (q *Queries) ListActiveRangeTemplates(ctx context.Context) ([]ListActiveRangeTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listActiveRangeTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRangeTemplatesRow{}
	for rows.Next() {
		var i ListActiveRangeTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.TtlSeconds,
			&i.CpuMillis,
			&i.MemoryMib,
			&i.StorageMib,
			&i.Spec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRanges = `-- name: ListExpiredRanges :many
SELECT id FROM ranges
WHERE state IN ('READY', 'ACTIVE') AND expires_at <= now()
ORDER BY expires_at
LIMIT $1
`

func (q *Queries) ListExpiredRanges(ctx context.Context, maxRows int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredRanges, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRanges = `-- name: ListPendingRanges :many
SELECT id, player_id, template_id, state, namespace, requested_cpu_millis, requested_memory_mib, requested_storage_mib, failure_reason, expires_at, ready_at, destroyed_at, created_at, updated_at FROM ranges WHERE state IN ('REQUESTED', 'QUEUED')
ORDER BY created_at, id
LIMIT $1
FOR UPDATE
`

// Ranges waiting for capacity, first come first served.
func (q *Queries) ListPendingRanges(ctx context.Context, maxRows int32) ([]Range, error) {
	rows, err := q.db.Query(ctx, listPendingRanges, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Range{}
	for rows.Next() {
		var i Range
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.TemplateID,
			&i.State,
			&i.Namespace,
			&i.RequestedCpuMillis,
			&i.RequestedMemoryMib,
			&i.RequestedStorageMib,
			&i.FailureReason,
			&i.ExpiresAt,
			&i.ReadyAt,
			&i.DestroyedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRanges = `-- name: ListPlayerRanges :many
SELECT r.id, r.player_id, r.template_id, r.state, r.namespace, r.requested_cpu_millis, r.requested_memory_mib, r.requested_storage_mib, r.failure_reason, r.expires_at, r.ready_at, r.destroyed_at, r.created_at, r.updated_at, t.slug AS template_slug, t.name AS template_name, p.user_id
FROM ranges r
JOIN range_templates t ON t.id = r.template_id
JOIN players p ON p.id = r.player_id
WHERE r.player_id = $1
  AND ($2::uuid IS NULL OR r.id < $2::uuid)
ORDER BY r.id DESC
LIMIT $3
`

type ListPlayerRangesParams struct {
	PlayerID uuid.UUID
	BeforeID *uuid.UUID
	PageSize int32
}

type ListPlayerRangesRow struct {
	Range        Range
	TemplateSlug string
	TemplateName string
	UserID       uuid.UUID
}

// Newest first; pass the last id of the previous page as before_id.
func (q *Queries) ListPlayerRanges(ctx context.Context, arg ListPlayerRangesParams) ([]ListPlayerRangesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRanges, arg.PlayerID, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRangesRow{}
	for rows.Next() {
		var i ListPlayerRangesRow
		if err := rows.Scan(
			&i.Range.ID,
			&i.Range.PlayerID,
			&i.Range.TemplateID,
			&i.Range.State,
			&i.Range.Namespace,
			&i.Range.RequestedCpuMillis,
			&i.Range.RequestedMemoryMib,
			&i.Range.RequestedStorageMib,
			&i.Range.FailureReason,
			&i.Range.ExpiresAt,
			&i.Range.ReadyAt,
			&i.Range.DestroyedAt,
			&i.Range.CreatedAt,
			&i.Range.UpdatedAt,
			&i.TemplateSlug,
			&i.TemplateName,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRangeTransitions = `-- name: ListRangeTransitions :many
SELECT from_state, to_state, reason, actor, created_at
FROM range_state_transitions WHERE range_id = $1 ORDER BY id
`

type ListRangeTransitionsRow struct {
	FromState *string
	ToState   string
	Reason    string
	Actor     string
	CreatedAt time.Time
}

func (q *Queries) ListRangeTransitions(ctx context.Context, rangeID uuid.UUID) ([]ListRangeTransitionsRow, error) {
	rows, err := q.db.Query(ctx, listRangeTransitions, rangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRangeTransitionsRow{}
	for rows.Next() {
		var i ListRangeTransitionsRow
		if err := rows.Scan(
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRangesWithNamespaces = `-- name: ListRangesWithNamespaces :many
SELECT id, state, namespace, updated_at FROM ranges
WHERE state NOT IN ('REQUESTED', 'QUEUED', 'DESTROYED')
`

type ListRangesWithNamespacesRow struct {
	ID        uuid.UUID
	State     string
	Namespace string
	UpdatedAt time.Time
}

// Ranges whose namespace may exist in the cluster (reconciliation).
func (q *Queries) ListRangesWithNamespaces(ctx context.Context) ([]ListRangesWithNamespacesRow, error) {
	rows, err := q.db.Query(ctx, listRangesWithNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRangesWithNamespacesRow{}
	for rows.Next() {
		var i ListRangesWithNamespacesRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Namespace,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckRanges = `-- name: ListStuckRanges :many
SELECT r.id, r.state FROM ranges r
WHERE r.state IN ('PROVISIONING', 'STARTING', 'FAILED', 'EXPIRED', 'STOPPING')
  AND r.updated_at < now() - make_interval(secs => $1::float8)
  AND NOT EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.kind IN ('range.provision', 'range.destroy')
        AND j.state IN ('queued', 'running')
        AND j.payload ->> 'range_id' = r.id::text)
ORDER BY r.updated_at
LIMIT $2
`

type ListStuckRangesParams struct {
	StaleSeconds float64
	MaxRows      int32
}

type ListStuckRangesRow struct {
	ID    uuid.UUID
	State string
}

// Ranges in a state that needs a job, without one queued or running, and
// unchanged for longer than stale_seconds (the job failed permanently or
// was lost). The reconciler re-drives them.
func (q *Queries) ListStuckRanges(ctx context.Context, arg ListStuckRangesParams) ([]ListStuckRangesRow, error) {
	rows, err := q.db.Query(ctx, listStuckRanges, arg.StaleSeconds, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckRangesRow{}
	for rows.Next() {
		var i ListStuckRangesRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRangeAdmission = `-- name: LockRangeAdmission :exec
SELECT pg_advisory_xact_lock(hashtextextended('range-admission', 0))
`

// Serialises capacity decisions across workers for the transaction.
func (q *Queries) LockRangeAdmission(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRangeAdmission)
	return err
}

const rangeStatesByID = `-- name: RangeStatesByID :many
SELECT id, state, updated_at FROM ranges WHERE id = ANY($1::uuid[])
`

type RangeStatesByIDRow struct {
	ID        uuid.UUID
	State     string
	UpdatedAt time.Time
}

func (q *Queries) RangeStatesByID(ctx context.Context, ids []uuid.UUID) ([]RangeStatesByIDRow, error) {
	rows, err := q.db.Query(ctx, rangeStatesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RangeStatesByIDRow{}
	for rows.Next() {
		var i RangeStatesByIDRow
		if err := rows.Scan(&i.ID, &i.State, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRangeResources = `-- name: RecordRangeResources :exec
INSERT INTO range_resources (range_id, kind, name)
SELECT $1::uuid, unnest($2::text[]), unnest($3::text[])
ON CONFLICT DO NOTHING
`

type RecordRangeResourcesParams struct {
	RangeID uuid.UUID
	Kinds   []string
	Names   []string
}

func (q *Queries) RecordRangeResources(ctx context.Context, arg RecordRangeResourcesParams) error {
	_, err := q.db.Exec(ctx, recordRangeResources, arg.RangeID, arg.Kinds, arg.Names)
	return err
}

const sumRangeUsage = `-- name: SumRangeUsage :one
SELECT COALESCE(sum(requested_cpu_millis), 0)::bigint AS cpu_millis,
       COALESCE(sum(requested_memory_mib), 0)::bigint AS memory_mib,
       COALESCE(sum(requested_storage_mib), 0)::bigint AS storage_mib,
       count(*)::int AS ranges
FROM ranges WHERE state = ANY($1::text[])
`

type SumRangeUsageRow struct {
	CpuMillis  int64
	MemoryMib  int64
	StorageMib int64
	Ranges     int32
}

// Resources reserved by ranges in the given (capacity-consuming) states.
func (q *Queries) SumRangeUsage(ctx context.Context, states []string) (SumRangeUsageRow, error) {
	row := q.db.QueryRow(ctx, sumRangeUsage, states)
	var i SumRangeUsageRow
	err := row.Scan(
		&i.CpuMillis,
		&i.MemoryMib,
		&i.StorageMib,
		&i.Ranges,
	)
	return i, err
}

const transitionRange = `-- name: TransitionRange :one
UPDATE ranges r
SET state = $1::text,
    failure_reason = CASE WHEN $1::text = 'FAILED' THEN $2::text ELSE r.failure_reason END,
    ready_at = CASE WHEN $1::text = 'READY' THEN now() ELSE r.ready_at END,
    expires_at = CASE WHEN $1::text = 'READY'
        THEN now() + make_interval(secs => (SELECT t.ttl_seconds FROM range_templates t WHERE t.id = r.template_id))
        ELSE r.expires_at END,
    destroyed_at = CASE WHEN $1::text = 'DESTROYED' THEN now() ELSE NULL END
WHERE r.id = $3 AND r.state = $4::text
RETURNING id, player_id, template_id, state, namespace, requested_cpu_millis, requested_memory_mib, requested_storage_mib, failure_reason, expires_at, ready_at, destroyed_at, created_at, updated_at
`

type TransitionRangeParams struct {
	ToState   string
	Reason    string
	ID        uuid.UUID
	FromState string
}

// Compare-and-set state change: it only applies if the range is still in
// from_state, so concurrent actors (API, worker, expiry, reconciler) can
// never overwrite each other's transitions.
func (q *Queries) TransitionRange(ctx context.Context, arg TransitionRangeParams) (Range, error) {
	row := q.db.QueryRow(ctx, transitionRange,
		arg.ToState,
		arg.Reason,
		arg.ID,
		arg.FromState,
	)
	var i Range
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TemplateID,
		&i.State,
		&i.Namespace,
		&i.RequestedCpuMillis,
		&i.RequestedMemoryMib,
		&i.RequestedStorageMib,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.ReadyAt,
		&i.DestroyedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRangeTemplate = `-- name: UpsertRangeTemplate :one

INSERT INTO range_templates (scenario_id, slug, name, description, ttl_seconds, cpu_millis, memory_mib, storage_mib, spec, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, true)
ON CONFLICT (scenario_id, slug) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description, ttl_seconds = EXCLUDED.ttl_seconds,
    cpu_millis = EXCLUDED.cpu_millis, memory_mib = EXCLUDED.memory_mib, storage_mib = EXCLUDED.storage_mib,
    spec = EXCLUDED.spec, active = true
RETURNING id
`

type UpsertRangeTemplateParams struct {
	ScenarioID  uuid.UUID
	Slug        string
	Name        string
	Description string
	TtlSeconds  int32
	CpuMillis   int32
	MemoryMib   int32
	StorageMib  int32
	Spec        []byte
}

// Range templates and per-player cyber ranges (see internal/cyberrange).
func (q *Queries) UpsertRangeTemplate(ctx context.Context, arg UpsertRangeTemplateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRangeTemplate,
		arg.ScenarioID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.TtlSeconds,
		arg.CpuMillis,
		arg.MemoryMib,
		arg.StorageMib,
		arg.Spec,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
