// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenario_import.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearAssetAddresses = `-- name: ClearAssetAddresses :exec
UPDATE assets SET hostname = NULL, ip_address = NULL
WHERE company_id = $1 AND (hostname IS NOT NULL OR ip_address IS NOT NULL)
`

// Run before upserting so hostnames/IPs can move between assets within one
// import without tripping the per-company unique indexes.
func (q *Queries) ClearAssetAddresses(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssetAddresses, companyID)
	return err
}

const deactivateOtherScenarios = `-- name: DeactivateOtherScenarios :exec
UPDATE scenarios SET is_active = false WHERE is_active AND id <> $1
`

func (q *Queries) DeactivateOtherScenarios(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateOtherScenarios, id)
	return err
}

const deleteCompanyRelationships = `-- name: DeleteCompanyRelationships :exec
DELETE FROM asset_relationships WHERE company_id = $1
`

func (q *Queries) DeleteCompanyRelationships(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompanyRelationships, companyID)
	return err
}

const deleteCompanySchedules = `-- name: DeleteCompanySchedules :exec
DELETE FROM employee_schedules s
USING employees e
WHERE s.employee_id = e.id AND e.company_id = $1
`

func (q *Queries) DeleteCompanySchedules(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompanySchedules, companyID)
	return err
}

const deleteStaleAssets = `-- name: DeleteStaleAssets :execrows
DELETE FROM assets WHERE company_id = $1 AND NOT (asset_code = ANY($2::text[]))
`

type DeleteStaleAssetsParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleAssets(ctx context.Context, arg DeleteStaleAssetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAssets, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleDepartments = `-- name: DeleteStaleDepartments :execrows
DELETE FROM departments WHERE company_id = $1 AND NOT (code = ANY($2::text[]))
`

type DeleteStaleDepartmentsParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleDepartments(ctx context.Context, arg DeleteStaleDepartmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDepartments, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleEmployees = `-- name: DeleteStaleEmployees :execrows
DELETE FROM employees WHERE company_id = $1 AND NOT (employee_code = ANY($2::text[]))
`

type DeleteStaleEmployeesParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleEmployees(ctx context.Context, arg DeleteStaleEmployeesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleEmployees, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleIdentities = `-- name: DeleteStaleIdentities :execrows
DELETE FROM enterprise_identities WHERE company_id = $1 AND NOT (username = ANY($2::text[]))
`

type DeleteStaleIdentitiesParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleIdentities(ctx context.Context, arg DeleteStaleIdentitiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleIdentities, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleLocations = `-- name: DeleteStaleLocations :execrows
DELETE FROM locations WHERE company_id = $1 AND NOT (code = ANY($2::text[]))
`

type DeleteStaleLocationsParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleLocations(ctx context.Context, arg DeleteStaleLocationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleLocations, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleWorldObjects = `-- name: DeleteStaleWorldObjects :execrows
DELETE FROM world_objects WHERE company_id = $1 AND NOT (object_key = ANY($2::text[]))
`

type DeleteStaleWorldObjectsParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleWorldObjects(ctx context.Context, arg DeleteStaleWorldObjectsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleWorldObjects, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleZones = `-- name: DeleteStaleZones :execrows
DELETE FROM world_zones WHERE company_id = $1 AND NOT (code = ANY($2::text[]))
`

type DeleteStaleZonesParams struct {
	CompanyID uuid.UUID
	Keep      []string
}

func (q *Queries) DeleteStaleZones(ctx context.Context, arg DeleteStaleZonesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleZones, arg.CompanyID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanyIDByScenario = `-- name: GetCompanyIDByScenario :one
SELECT id FROM companies WHERE scenario_id = $1
`

func (q *Queries) GetCompanyIDByScenario(ctx context.Context, scenarioID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCompanyIDByScenario, scenarioID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getScenarioBySlug = `-- name: GetScenarioBySlug :one

SELECT id, slug, name, version, description, status, is_active, content_hash, imported_at, published_at, created_at, updated_at FROM scenarios WHERE slug = $1
`

// Write side of the scenario importer. Entities are upserted by natural key
// so their IDs survive re-imports; anything no longer present in the
// scenario files is pruned with the Delete* queries.
func (q *Queries) GetScenarioBySlug(ctx context.Context, slug string) (Scenario, error) {
	row := q.db.QueryRow(ctx, getScenarioBySlug, slug)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Status,
		&i.IsActive,
		&i.ContentHash,
		&i.ImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRelationship = `-- name: InsertRelationship :exec
INSERT INTO asset_relationships (
    company_id, relationship_type,
    source_employee_id, source_identity_id, source_asset_id,
    target_employee_id, target_identity_id, target_asset_id
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7, $8
)
ON CONFLICT ON CONSTRAINT asset_relationships_unique_key DO NOTHING
`

type InsertRelationshipParams struct {
	CompanyID        uuid.UUID
	RelationshipType string
	SourceEmployeeID *uuid.UUID
	SourceIdentityID *uuid.UUID
	SourceAssetID    *uuid.UUID
	TargetEmployeeID *uuid.UUID
	TargetIdentityID *uuid.UUID
	TargetAssetID    *uuid.UUID
}

func (q *Queries) InsertRelationship(ctx context.Context, arg InsertRelationshipParams) error {
	_, err := q.db.Exec(ctx, insertRelationship,
		arg.CompanyID,
		arg.RelationshipType,
		arg.SourceEmployeeID,
		arg.SourceIdentityID,
		arg.SourceAssetID,
		arg.TargetEmployeeID,
		arg.TargetIdentityID,
		arg.TargetAssetID,
	)
	return err
}

const insertSchedule = `-- name: InsertSchedule :exec
INSERT INTO employee_schedules (employee_id, weekday, starts_at, ends_at, location_id, activity)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertScheduleParams struct {
	EmployeeID uuid.UUID
	Weekday    int32
	StartsAt   pgtype.Time
	EndsAt     pgtype.Time
	LocationID *uuid.UUID
	Activity   string
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) error {
	_, err := q.db.Exec(ctx, insertSchedule,
		arg.EmployeeID,
		arg.Weekday,
		arg.StartsAt,
		arg.EndsAt,
		arg.LocationID,
		arg.Activity,
	)
	return err
}

const lockScenarioImport = `-- name: LockScenarioImport :exec
SELECT pg_advisory_xact_lock(hashtextextended('scenario-import:' || $1::text, 0))
`

// Serialises concurrent imports of the same scenario for the transaction.
func (q *Queries) LockScenarioImport(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, lockScenarioImport, slug)
	return err
}

const publishAndActivateScenario = `-- name: PublishAndActivateScenario :exec
UPDATE scenarios
SET status       = 'published',
    published_at = COALESCE(published_at, now()),
    is_active    = true
WHERE id = $1
`

func (q *Queries) PublishAndActivateScenario(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, publishAndActivateScenario, id)
	return err
}

const setDepartmentLinks = `-- name: SetDepartmentLinks :exec
UPDATE departments
SET parent_id = $1, head_employee_id = $2
WHERE id = $3
`

type SetDepartmentLinksParams struct {
	ParentID       *uuid.UUID
	HeadEmployeeID *uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) SetDepartmentLinks(ctx context.Context, arg SetDepartmentLinksParams) error {
	_, err := q.db.Exec(ctx, setDepartmentLinks, arg.ParentID, arg.HeadEmployeeID, arg.ID)
	return err
}

const setEmployeeManager = `-- name: SetEmployeeManager :exec
UPDATE employees SET manager_id = $1 WHERE id = $2
`

type SetEmployeeManagerParams struct {
	ManagerID *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SetEmployeeManager(ctx context.Context, arg SetEmployeeManagerParams) error {
	_, err := q.db.Exec(ctx, setEmployeeManager, arg.ManagerID, arg.ID)
	return err
}

const setZoneParent = `-- name: SetZoneParent :exec
UPDATE world_zones SET parent_id = $1 WHERE id = $2
`

type SetZoneParentParams struct {
	ParentID *uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetZoneParent(ctx context.Context, arg SetZoneParentParams) error {
	_, err := q.db.Exec(ctx, setZoneParent, arg.ParentID, arg.ID)
	return err
}

const upsertAsset = `-- name: UpsertAsset :one
INSERT INTO assets (
    company_id, asset_code, name, asset_type, hostname, ip_address, network_cidr, operating_system,
    criticality, status, department_id, owner_employee_id, location_id, description, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15
)
ON CONFLICT (company_id, asset_code) DO UPDATE
SET name              = EXCLUDED.name,
    asset_type        = EXCLUDED.asset_type,
    hostname          = EXCLUDED.hostname,
    ip_address        = EXCLUDED.ip_address,
    network_cidr      = EXCLUDED.network_cidr,
    operating_system  = EXCLUDED.operating_system,
    criticality       = EXCLUDED.criticality,
    status            = EXCLUDED.status,
    department_id     = EXCLUDED.department_id,
    owner_employee_id = EXCLUDED.owner_employee_id,
    location_id       = EXCLUDED.location_id,
    description       = EXCLUDED.description,
    attributes        = EXCLUDED.attributes
RETURNING id
`

type UpsertAssetParams struct {
	CompanyID       uuid.UUID
	AssetCode       string
	Name            string
	AssetType       string
	Hostname        *string
	IPAddress       *netip.Addr
	NetworkCIDR     *netip.Prefix
	OperatingSystem *string
	Criticality     string
	Status          string
	DepartmentID    *uuid.UUID
	OwnerEmployeeID *uuid.UUID
	LocationID      *uuid.UUID
	Description     string
	Attributes      []byte
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAsset,
		arg.CompanyID,
		arg.AssetCode,
		arg.Name,
		arg.AssetType,
		arg.Hostname,
		arg.IPAddress,
		arg.NetworkCIDR,
		arg.OperatingSystem,
		arg.Criticality,
		arg.Status,
		arg.DepartmentID,
		arg.OwnerEmployeeID,
		arg.LocationID,
		arg.Description,
		arg.Attributes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (scenario_id, code, name, legal_name, industry, description, headquarters, founded_year, email_domain)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (scenario_id) DO UPDATE
SET code         = EXCLUDED.code,
    name         = EXCLUDED.name,
    legal_name   = EXCLUDED.legal_name,
    industry     = EXCLUDED.industry,
    description  = EXCLUDED.description,
    headquarters = EXCLUDED.headquarters,
    founded_year = EXCLUDED.founded_year,
    email_domain = EXCLUDED.email_domain
RETURNING id
`

type UpsertCompanyParams struct {
	ScenarioID   uuid.UUID
	Code         string
	Name         string
	LegalName    string
	Industry     string
	Description  string
	Headquarters string
	FoundedYear  *int32
	EmailDomain  string
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.ScenarioID,
		arg.Code,
		arg.Name,
		arg.LegalName,
		arg.Industry,
		arg.Description,
		arg.Headquarters,
		arg.FoundedYear,
		arg.EmailDomain,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertDepartment = `-- name: UpsertDepartment :one
INSERT INTO departments (company_id, code, name, description, sort_order)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_id, code) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description, sort_order = EXCLUDED.sort_order
RETURNING id
`

type UpsertDepartmentParams struct {
	CompanyID   uuid.UUID
	Code        string
	Name        string
	Description string
	SortOrder   int32
}

func (q *Queries) UpsertDepartment(ctx context.Context, arg UpsertDepartmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDepartment,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertEmployee = `-- name: UpsertEmployee :one
INSERT INTO employees (
    company_id, employee_code, first_name, last_name, display_name, job_title,
    department_id, home_location_id, employment_type, status, is_npc, persona, greeting
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (company_id, employee_code) DO UPDATE
SET first_name       = EXCLUDED.first_name,
    last_name        = EXCLUDED.last_name,
    display_name     = EXCLUDED.display_name,
    job_title        = EXCLUDED.job_title,
    department_id    = EXCLUDED.department_id,
    home_location_id = EXCLUDED.home_location_id,
    employment_type  = EXCLUDED.employment_type,
    status           = EXCLUDED.status,
    is_npc           = EXCLUDED.is_npc,
    persona          = EXCLUDED.persona,
    greeting         = EXCLUDED.greeting
RETURNING id
`

type UpsertEmployeeParams struct {
	CompanyID      uuid.UUID
	EmployeeCode   string
	FirstName      string
	LastName       string
	DisplayName    string
	JobTitle       string
	DepartmentID   uuid.UUID
	HomeLocationID *uuid.UUID
	EmploymentType string
	Status         string
	IsNpc          bool
	Persona        string
	Greeting       string
}

func (q *Queries) UpsertEmployee(ctx context.Context, arg UpsertEmployeeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertEmployee,
		arg.CompanyID,
		arg.EmployeeCode,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.JobTitle,
		arg.DepartmentID,
		arg.HomeLocationID,
		arg.EmploymentType,
		arg.Status,
		arg.IsNpc,
		arg.Persona,
		arg.Greeting,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertIdentity = `-- name: UpsertIdentity :one
INSERT INTO enterprise_identities (
    company_id, employee_id, username, email, identity_type, status, mfa_enabled, privileged, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (company_id, username) DO UPDATE
SET employee_id   = EXCLUDED.employee_id,
    email         = EXCLUDED.email,
    identity_type = EXCLUDED.identity_type,
    status        = EXCLUDED.status,
    mfa_enabled   = EXCLUDED.mfa_enabled,
    privileged    = EXCLUDED.privileged,
    expires_at    = EXCLUDED.expires_at
RETURNING id
`

type UpsertIdentityParams struct {
	CompanyID    uuid.UUID
	EmployeeID   *uuid.UUID
	Username     string
	Email        string
	IdentityType string
	Status       string
	MfaEnabled   bool
	Privileged   bool
	ExpiresAt    *time.Time
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertIdentity,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Username,
		arg.Email,
		arg.IdentityType,
		arg.Status,
		arg.MfaEnabled,
		arg.Privileged,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertLocation = `-- name: UpsertLocation :one
INSERT INTO locations (company_id, zone_id, code, name, kind, department_id, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (company_id, code) DO UPDATE
SET zone_id       = EXCLUDED.zone_id,
    name          = EXCLUDED.name,
    kind          = EXCLUDED.kind,
    department_id = EXCLUDED.department_id,
    description   = EXCLUDED.description
RETURNING id
`

type UpsertLocationParams struct {
	CompanyID    uuid.UUID
	ZoneID       uuid.UUID
	Code         string
	Name         string
	Kind         string
	DepartmentID *uuid.UUID
	Description  string
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertLocation,
		arg.CompanyID,
		arg.ZoneID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.DepartmentID,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertScenario = `-- name: UpsertScenario :one
INSERT INTO scenarios (slug, name, version, description, content_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (slug) DO UPDATE
SET name         = EXCLUDED.name,
    version      = EXCLUDED.version,
    description  = EXCLUDED.description,
    content_hash = EXCLUDED.content_hash,
    imported_at  = now()
RETURNING id, (xmax = 0)::boolean AS inserted
`

type UpsertScenarioParams struct {
	Slug        string
	Name        string
	Version     string
	Description string
	ContentHash string
}

type UpsertScenarioRow struct {
	ID       uuid.UUID
	Inserted bool
}

func (q *Queries) UpsertScenario(ctx context.Context, arg UpsertScenarioParams) (UpsertScenarioRow, error) {
	row := q.db.QueryRow(ctx, upsertScenario,
		arg.Slug,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.ContentHash,
	)
	var i UpsertScenarioRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const upsertWorldObject = `-- name: UpsertWorldObject :one
INSERT INTO world_objects (
    company_id, location_id, object_key, name, kind, asset_id, leads_to_zone_id,
    interactions, description, content, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (company_id, object_key) DO UPDATE
SET location_id      = EXCLUDED.location_id,
    name             = EXCLUDED.name,
    kind             = EXCLUDED.kind,
    asset_id         = EXCLUDED.asset_id,
    leads_to_zone_id = EXCLUDED.leads_to_zone_id,
    interactions     = EXCLUDED.interactions,
    description      = EXCLUDED.description,
    content          = EXCLUDED.content,
    attributes       = EXCLUDED.attributes
RETURNING id
`

type UpsertWorldObjectParams struct {
	CompanyID     uuid.UUID
	LocationID    uuid.UUID
	ObjectKey     string
	Name          string
	Kind          string
	AssetID       *uuid.UUID
	LeadsToZoneID *uuid.UUID
	Interactions  []string
	Description   string
	Content       string
	Attributes    []byte
}

func (q *Queries) UpsertWorldObject(ctx context.Context, arg UpsertWorldObjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertWorldObject,
		arg.CompanyID,
		arg.LocationID,
		arg.ObjectKey,
		arg.Name,
		arg.Kind,
		arg.AssetID,
		arg.LeadsToZoneID,
		arg.Interactions,
		arg.Description,
		arg.Content,
		arg.Attributes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertZone = `-- name: UpsertZone :one
INSERT INTO world_zones (company_id, code, name, kind, description, unlocked_by_default, required_career_rank, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (company_id, code) DO UPDATE
SET name                 = EXCLUDED.name,
    kind                 = EXCLUDED.kind,
    description          = EXCLUDED.description,
    unlocked_by_default  = EXCLUDED.unlocked_by_default,
    required_career_rank = EXCLUDED.required_career_rank,
    sort_order           = EXCLUDED.sort_order
RETURNING id
`

type UpsertZoneParams struct {
	CompanyID          uuid.UUID
	Code               string
	Name               string
	Kind               string
	Description        string
	UnlockedByDefault  bool
	RequiredCareerRank int32
	SortOrder          int32
}

func (q *Queries) UpsertZone(ctx context.Context, arg UpsertZoneParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertZone,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.UnlockedByDefault,
		arg.RequiredCareerRank,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
