// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlayerIDByUserID = `-- name: GetPlayerIDByUserID :one
SELECT id FROM players WHERE user_id = $1
`

func (q *Queries) GetPlayerIDByUserID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPlayerIDByUserID, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
    u.id,
    u.username,
    u.email,
    u.email_verified,
    u.full_name,
    u.status,
    u.created_at,
    p.id           AS player_id,
    p.display_name AS player_display_name,
    p.created_at   AS player_created_at
FROM users u
LEFT JOIN players p ON p.user_id = u.id
WHERE u.id = $1
`

type GetUserProfileRow struct {
	ID                uuid.UUID
	Username          string
	Email             *string
	EmailVerified     bool
	FullName          *string
	Status            string
	CreatedAt         time.Time
	PlayerID          *uuid.UUID
	PlayerDisplayName *string
	PlayerCreatedAt   *time.Time
}

// The user together with their player profile, if any.
func (q *Queries) GetUserProfile(ctx context.Context, userID uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.PlayerID,
		&i.PlayerDisplayName,
		&i.PlayerCreatedAt,
	)
	return i, err
}

const insertPlayerIfMissing = `-- name: InsertPlayerIfMissing :one
INSERT INTO players (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
RETURNING id
`

type InsertPlayerIfMissingParams struct {
	UserID      uuid.UUID
	DisplayName string
}

// Returns the new player's id, or no rows if the user already has one.
func (q *Queries) InsertPlayerIfMissing(ctx context.Context, arg InsertPlayerIfMissingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlayerIfMissing, arg.UserID, arg.DisplayName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertUserFromToken = `-- name: UpsertUserFromToken :one
INSERT INTO users (keycloak_subject, username, email, email_verified, full_name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (keycloak_subject) DO UPDATE
SET username       = EXCLUDED.username,
    email          = EXCLUDED.email,
    email_verified = EXCLUDED.email_verified,
    full_name      = EXCLUDED.full_name,
    last_seen_at   = now()
RETURNING id, status, (xmax = 0)::boolean AS inserted
`

type UpsertUserFromTokenParams struct {
	KeycloakSubject string
	Username        string
	Email           *string
	EmailVerified   bool
	FullName        *string
}

type UpsertUserFromTokenRow struct {
	ID       uuid.UUID
	Status   string
	Inserted bool
}

// Creates the user on first sight and refreshes the mirrored profile
// otherwise. The update always runs (last_seen_at changes) so RETURNING
// yields a row in both cases; xmax = 0 identifies a fresh insert.
func (q *Queries) UpsertUserFromToken(ctx context.Context, arg UpsertUserFromTokenParams) (UpsertUserFromTokenRow, error) {
	row := q.db.QueryRow(ctx, upsertUserFromToken,
		arg.KeycloakSubject,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.FullName,
	)
	var i UpsertUserFromTokenRow
	err := row.Scan(&i.ID, &i.Status, &i.Inserted)
	return i, err
}
