// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: world.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const getWorldObjectByKey = `-- name: GetWorldObjectByKey :one
SELECT o.id, o.object_key, o.name, o.kind, o.interactions, o.description, o.attributes,
       l.id AS location_id, l.code AS location_code, l.name AS location_name,
       z.id AS zone_id, z.code AS zone_code, z.name AS zone_name,
       t.id AS leads_to_zone_id, t.code AS leads_to_zone_code,
       a.id AS asset_id, a.asset_code, a.name AS asset_name, a.asset_type, a.hostname, a.ip_address,
       a.operating_system, a.criticality,
       ad.code AS asset_department_code,
       ao.employee_code AS asset_owner_code, ao.display_name AS asset_owner_name
FROM world_objects o
JOIN locations l ON l.id = o.location_id
JOIN world_zones z ON z.id = l.zone_id
LEFT JOIN world_zones t ON t.id = o.leads_to_zone_id
LEFT JOIN assets a ON a.id = o.asset_id
LEFT JOIN departments ad ON ad.id = a.department_id
LEFT JOIN employees ao ON ao.id = a.owner_employee_id
WHERE o.company_id = $1 AND o.object_key = $2
`

type GetWorldObjectByKeyParams struct {
	CompanyID uuid.UUID
	ObjectKey string
}

type GetWorldObjectByKeyRow struct {
	ID                  uuid.UUID
	ObjectKey           string
	Name                string
	Kind                string
	Interactions        []string
	Description         string
	Attributes          []byte
	LocationID          uuid.UUID
	LocationCode        string
	LocationName        string
	ZoneID              uuid.UUID
	ZoneCode            string
	ZoneName            string
	LeadsToZoneID       *uuid.UUID
	LeadsToZoneCode     *string
	AssetID             *uuid.UUID
	AssetCode           *string
	AssetName           *string
	AssetType           *string
	Hostname            *string
	IPAddress           *netip.Addr
	OperatingSystem     *string
	Criticality         *string
	AssetDepartmentCode *string
	AssetOwnerCode      *string
	AssetOwnerName      *string
}

func (q *Queries) GetWorldObjectByKey(ctx context.Context, arg GetWorldObjectByKeyParams) (GetWorldObjectByKeyRow, error) {
	row := q.db.QueryRow(ctx, getWorldObjectByKey, arg.CompanyID, arg.ObjectKey)
	var i GetWorldObjectByKeyRow
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Name,
		&i.Kind,
		&i.Interactions,
		&i.Description,
		&i.Attributes,
		&i.LocationID,
		&i.LocationCode,
		&i.LocationName,
		&i.ZoneID,
		&i.ZoneCode,
		&i.ZoneName,
		&i.LeadsToZoneID,
		&i.LeadsToZoneCode,
		&i.AssetID,
		&i.AssetCode,
		&i.AssetName,
		&i.AssetType,
		&i.Hostname,
		&i.IPAddress,
		&i.OperatingSystem,
		&i.Criticality,
		&i.AssetDepartmentCode,
		&i.AssetOwnerCode,
		&i.AssetOwnerName,
	)
	return i, err
}

const getZone = `-- name: GetZone :one
SELECT z.id, z.code, z.name, z.kind, z.description, z.unlocked_by_default, z.required_career_rank,
       p.id AS parent_id, p.code AS parent_code
FROM world_zones z
LEFT JOIN world_zones p ON p.id = z.parent_id
WHERE z.company_id = $1 AND z.id = $2
`

type GetZoneParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type GetZoneRow struct {
	ID                 uuid.UUID
	Code               string
	Name               string
	Kind               string
	Description        string
	UnlockedByDefault  bool
	RequiredCareerRank int32
	ParentID           *uuid.UUID
	ParentCode         *string
}

func (q *Queries) GetZone(ctx context.Context, arg GetZoneParams) (GetZoneRow, error) {
	row := q.db.QueryRow(ctx, getZone, arg.CompanyID, arg.ID)
	var i GetZoneRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.UnlockedByDefault,
		&i.RequiredCareerRank,
		&i.ParentID,
		&i.ParentCode,
	)
	return i, err
}

const listZoneEmployees = `-- name: ListZoneEmployees :many
SELECT e.id, e.employee_code, e.display_name, e.job_title, e.greeting, l.code AS location_code
FROM employees e
JOIN locations l ON l.id = e.home_location_id
WHERE e.company_id = $1 AND l.zone_id = $2 AND e.is_npc AND e.status = 'active'
ORDER BY e.employee_code
`

type ListZoneEmployeesParams struct {
	CompanyID uuid.UUID
	ZoneID    uuid.UUID
}

type ListZoneEmployeesRow struct {
	ID           uuid.UUID
	EmployeeCode string
	DisplayName  string
	JobTitle     string
	Greeting     string
	LocationCode string
}

// NPCs whose home location is in the zone. The living-company scheduler
// will move them during the day in a later phase.
func (q *Queries) ListZoneEmployees(ctx context.Context, arg ListZoneEmployeesParams) ([]ListZoneEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listZoneEmployees, arg.CompanyID, arg.ZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZoneEmployeesRow{}
	for rows.Next() {
		var i ListZoneEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.DisplayName,
			&i.JobTitle,
			&i.Greeting,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneLocations = `-- name: ListZoneLocations :many
SELECT l.id, l.code, l.name, l.kind, l.description, d.code AS department_code
FROM locations l
LEFT JOIN departments d ON d.id = l.department_id
WHERE l.company_id = $1 AND l.zone_id = $2
ORDER BY l.code
`

type ListZoneLocationsParams struct {
	CompanyID uuid.UUID
	ZoneID    uuid.UUID
}

type ListZoneLocationsRow struct {
	ID             uuid.UUID
	Code           string
	Name           string
	Kind           string
	Description    string
	DepartmentCode *string
}

func (q *Queries) ListZoneLocations(ctx context.Context, arg ListZoneLocationsParams) ([]ListZoneLocationsRow, error) {
	rows, err := q.db.Query(ctx, listZoneLocations, arg.CompanyID, arg.ZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZoneLocationsRow{}
	for rows.Next() {
		var i ListZoneLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.DepartmentCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneObjects = `-- name: ListZoneObjects :many
SELECT o.id, o.object_key, o.name, o.kind, o.interactions, o.description,
       l.code AS location_code,
       a.id AS asset_id, a.asset_code, a.name AS asset_name, a.asset_type, a.hostname, a.ip_address,
       t.id AS leads_to_zone_id, t.code AS leads_to_zone_code
FROM world_objects o
JOIN locations l ON l.id = o.location_id
LEFT JOIN assets a ON a.id = o.asset_id
LEFT JOIN world_zones t ON t.id = o.leads_to_zone_id
WHERE o.company_id = $1 AND l.zone_id = $2
ORDER BY o.object_key
`

type ListZoneObjectsParams struct {
	CompanyID uuid.UUID
	ZoneID    uuid.UUID
}

type ListZoneObjectsRow struct {
	ID              uuid.UUID
	ObjectKey       string
	Name            string
	Kind            string
	Interactions    []string
	Description     string
	LocationCode    string
	AssetID         *uuid.UUID
	AssetCode       *string
	AssetName       *string
	AssetType       *string
	Hostname        *string
	IPAddress       *netip.Addr
	LeadsToZoneID   *uuid.UUID
	LeadsToZoneCode *string
}

func (q *Queries) ListZoneObjects(ctx context.Context, arg ListZoneObjectsParams) ([]ListZoneObjectsRow, error) {
	rows, err := q.db.Query(ctx, listZoneObjects, arg.CompanyID, arg.ZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZoneObjectsRow{}
	for rows.Next() {
		var i ListZoneObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.Name,
			&i.Kind,
			&i.Interactions,
			&i.Description,
			&i.LocationCode,
			&i.AssetID,
			&i.AssetCode,
			&i.AssetName,
			&i.AssetType,
			&i.Hostname,
			&i.IPAddress,
			&i.LeadsToZoneID,
			&i.LeadsToZoneCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
SELECT z.id, z.code, z.name, z.kind, z.description, z.unlocked_by_default, z.required_career_rank,
       p.id AS parent_id, p.code AS parent_code
FROM world_zones z
LEFT JOIN world_zones p ON p.id = z.parent_id
WHERE z.company_id = $1
ORDER BY z.sort_order, z.code
`

type ListZonesRow struct {
	ID                 uuid.UUID
	Code               string
	Name               string
	Kind               string
	Description        string
	UnlockedByDefault  bool
	RequiredCareerRank int32
	ParentID           *uuid.UUID
	ParentCode         *string
}

func (q *Queries) ListZones(ctx context.Context, companyID uuid.UUID) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesRow{}
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.UnlockedByDefault,
			&i.RequiredCareerRank,
			&i.ParentID,
			&i.ParentCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
